/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangSocialDutyRouteImport } from './routes/$lang.social-duty'
import { Route as LangServicesRouteImport } from './routes/$lang.services'
import { Route as LangProjectsRouteImport } from './routes/$lang.projects'
import { Route as LangNewsRouteImport } from './routes/$lang.news'
import { Route as LangGalleryRouteImport } from './routes/$lang.gallery'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangCareersRouteImport } from './routes/$lang.careers'
import { Route as LangAboutRouteImport } from './routes/$lang.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangSocialDutyRoute = LangSocialDutyRouteImport.update({
  id: '/social-duty',
  path: '/social-duty',
  getParentRoute: () => LangRoute,
} as any)
const LangServicesRoute = LangServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LangRoute,
} as any)
const LangProjectsRoute = LangProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LangRoute,
} as any)
const LangNewsRoute = LangNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => LangRoute,
} as any)
const LangGalleryRoute = LangGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangCareersRoute = LangCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/careers': typeof LangCareersRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/social-duty': typeof LangSocialDutyRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/careers': typeof LangCareersRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/social-duty': typeof LangSocialDutyRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/careers': typeof LangCareersRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/social-duty': typeof LangSocialDutyRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/careers'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/news'
    | '/$lang/projects'
    | '/$lang/services'
    | '/$lang/social-duty'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/careers'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/news'
    | '/$lang/projects'
    | '/$lang/services'
    | '/$lang/social-duty'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/careers'
    | '/$lang/contact'
    | '/$lang/gallery'
    | '/$lang/news'
    | '/$lang/projects'
    | '/$lang/services'
    | '/$lang/social-duty'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/social-duty': {
      id: '/$lang/social-duty'
      path: '/social-duty'
      fullPath: '/$lang/social-duty'
      preLoaderRoute: typeof LangSocialDutyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/services': {
      id: '/$lang/services'
      path: '/services'
      fullPath: '/$lang/services'
      preLoaderRoute: typeof LangServicesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/projects': {
      id: '/$lang/projects'
      path: '/projects'
      fullPath: '/$lang/projects'
      preLoaderRoute: typeof LangProjectsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/news': {
      id: '/$lang/news'
      path: '/news'
      fullPath: '/$lang/news'
      preLoaderRoute: typeof LangNewsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/gallery': {
      id: '/$lang/gallery'
      path: '/gallery'
      fullPath: '/$lang/gallery'
      preLoaderRoute: typeof LangGalleryRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/careers': {
      id: '/$lang/careers'
      path: '/careers'
      fullPath: '/$lang/careers'
      preLoaderRoute: typeof LangCareersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangCareersRoute: typeof LangCareersRoute
  LangContactRoute: typeof LangContactRoute
  LangGalleryRoute: typeof LangGalleryRoute
  LangNewsRoute: typeof LangNewsRoute
  LangProjectsRoute: typeof LangProjectsRoute
  LangServicesRoute: typeof LangServicesRoute
  LangSocialDutyRoute: typeof LangSocialDutyRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangCareersRoute: LangCareersRoute,
  LangContactRoute: LangContactRoute,
  LangGalleryRoute: LangGalleryRoute,
  LangNewsRoute: LangNewsRoute,
  LangProjectsRoute: LangProjectsRoute,
  LangServicesRoute: LangServicesRoute,
  LangSocialDutyRoute: LangSocialDutyRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
